import {
  IconHome,
  IconPayments,
  IconMonitorLine,
  IconGroup,
  IconComunicationDialog,
  IconCalendar,
  IconSecurity,
  IconBackOffice,
  IconFinance,
  IconAdministracion,
  IconCommunication,
  IconSecurityV2,
} from "../layout/icons/IconsBiblioteca";

export const menuConfig = [
  { type: "item", href: "/", label: "Inicio", perm: "home", icon: IconHome },
  {
    type: "dropdown",
    label: "Backoffice",
    icon: IconBackOffice,
    key: "Backoffice",
    items: [
      { href: "/superadmins", perm: "superadmins", label: "Superadmins" },
      { href: "/condominios", perm: "condominios", label: "Condominios" },
      { href: "/invitations", perm: "campanas", label: "Invitaciones QR" },
      { href: "/uploads", perm: "cargamasiva", label: "Carga masiva" },
    { href: "/app-versions", perm: "superadmins", label: "Versiones de App" },
    ],
  },
  {
    type: "dropdown",
    label: "Finanzas",
    icon: IconFinance,
    key: "Finanzas",
    items: [
      { href: "/balance", label: "Flujo de efectivo", perm: "balance" },
      {
        href: "/payments",
        label: "Ingresos",
        perm: "payments",
        badgeKey: "paymentsBage",
      },
      { href: "/outlays", label: "Egresos", perm: "outlays" },
      { href: "/expenses", label: "Expensas", perm: "expenses" },
      { href: "/defaulters", label: "Morosos", perm: "defaulters" },
      { href: "/debts_manager", label: "Deudas", perm: "debts_manager" },
      {
        href: "/bank-accounts",
        label: "Cuentas Bancarias",
        perm: "bank_accounts",
      },
      {
        href: "/partial-payments",
        label: "Pagos Parciales",
        perm: "bank_accounts",
      },
    ],
  },
  {
    type: "dropdown",
    label: "Administración",
    icon: IconAdministracion,
    key: "Administración",
    items: [
      { href: "/units", perm: "units", label: "Unidades" },
      { href: "/areas", perm: "areas", label: "Áreas sociales" },
      { href: "/documents", perm: "documents", label: "Documentos" },
      { href: "/configs", perm: "settings", label: "Configuración" },
    ],
  },
  {
    type: "dropdown",
    label: "Usuarios",
    icon: IconGroup,
    key: "Usuarios",
    items: [
      { href: "/owners", perm: "owners", label: "Residentes" },
      { href: "/users", perm: "users", label: "Personal Administrativo" },
      { href: "/roles", perm: "roles", label: "Roles y permisos" },
    ],
  },
  {
    type: "dropdown",
    label: "Comunicación",
    icon: IconCommunication,
    key: "Comunicación",
    items: [
      { href: "/contents", perm: "contents", label: "Publicaciones" },
      {
        href: "/reels",
        perm: "contents",
        label: "Muro publicaciones",
        badgeKey: "reelsBage",
      },
    ],
  },
  {
    type: "item",
    href: "/reservas",
    label: "Reservas",
    perm: "reservations",
    icon: IconCalendar,
    badgeKey: "reservasBage",
  },
  {
    type: "dropdown",
    label: "Vigilancia y seguridad",
    icon: IconSecurityV2,
    key: "Vigilancia y seguridad",
    items: [
      { href: "/guards", perm: "guards", label: "Guardias" },
      { href: "/activities", perm: "accesses", label: "Accesos" },
      {
        href: "/alerts",
        perm: "alerts",
        label: "Alertas",
        badgeKey: "alertsBage",
      },
      { href: "/binnacle", perm: "guardlogs", label: "Bitácora" },
    ],
  },
];
