const idioma: Record<string, string> = {
  "is required": "e obrigatorio",
  "must be the same": "deve ser igual",
  characters: "caracteres",
  min: "min",
  max: "max",
  "is not a valid value": "nao e um valor valido",
  "is not a valid email": "nao e um e-mail valido",
  "is not a number": "nao e um numero",
  "is not a valid text": "nao e um texto valido",
  "must be greater than": "deve ser maior que",
  "must be less than ": "deve ser menor que",
  "must be between ": "deve estar entre",
  and: "e",
  or: "ou",
  list: "lista de {0}",
  add: "adicionar",
  edit: "editar",
  delete: "excluir",
  update: "atualizar",
  view: "ver",
  save: "salvar",
  cancel: "cancelar",
  search: "Pesquisar",
  all: "todos",
  active: "ativo",
  inactive: "inativo",
  user: "usuario",
  admin: "administrador",
  adm: "administrador",
  team: "equipe",
  owner: "proprietario",
  actions: "acoes",
  "empty data": "sem dados",
  "are you sure you want to delete the record?":
    "tem certeza de que deseja excluir o registro?",
  settings: "configuracao",
  "sign out": "sair",
  wellcome: "bem-vindo",
  "password is required": "a senha e obrigatoria",
  "email is required": "o e-mail e obrigatorio",
  "welcome to": "bem-vindo a",
  "please sign-in to your account and start the adventure":
    "entre na sua conta para continuar",
  "sign in": "entrar",
  "advanced search": "pesquisa avancada",
  equal: "igual",
  "not equal": "diferente",
  contains: "contem",
  "not contains": "nao contem",
  "starts with": "comeca com",
  "ends with": "termina com",
  "greater than": "maior que",
  "less than": "menor que",
  "greater or equal": "maior ou igual",
  "less or equal": "menor ou igual",
  field: "campo",
  value: "valor",
  "search by": "buscar por",
  criteria: "criterio",
  yes: "sim",
  not: "nao",
};

export default idioma;
